/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#3c494e',
        'secondary-container': '#39485a',
        'error': '#ffb4ab',
        'on-tertiary': '#432c00',
        'on-primary-container': '#00586b',
        'on-surface': '#dde3e7',
        'surface-container-highest': '#2f3639',
        'surface-container': '#1a2123',
        'background': '#0e1417',
        'on-secondary-fixed': '#0d1d2d',
        'surface-glass': 'rgba(10, 31, 50, 0.6)',
        'on-secondary': '#233143',
        'on-tertiary-container': '#6c4900',
        'outline': '#859398',
        'surface-container-high': '#242b2e',
        'surface-container-low': '#161d1f',
        'surface-tint': '#3cd7ff',
        'primary-fixed-dim': '#3cd7ff',
        'on-background': '#dde3e7',
        'primary-fixed': '#b4ebff',
        'surface': '#0e1417',
        'secondary': '#b8c8de',
        'on-primary-fixed-variant': '#004e5f',
        'inverse-surface': '#dde3e7',
        'inverse-on-surface': '#2b3134',
        'tertiary': '#ffd9a1',
        'tech-gold': '#D4AF37',
        'on-tertiary-fixed': '#281900',
        'surface-dim': '#0e1417',
        'error-container': '#93000a',
        'tertiary-container': '#feb528',
        'surface-variant': '#2f3639',
        'on-primary': '#003642',
        'primary': '#a8e8ff',
        'on-secondary-container': '#a7b6cc',
        'secondary-fixed': '#d4e4fa',
        'inverse-primary': '#00677e',
        'surface-bright': '#333a3d',
        'text-muted': '#8A9BA8',
        'on-error': '#690005',
        'tertiary-fixed-dim': '#ffba3d',
        'on-tertiary-fixed-variant': '#604100',
        'on-surface-variant': '#bbc9cf',
        'on-error-container': '#ffdad6',
        'surface-container-lowest': '#080f12',
        'on-primary-fixed': '#001f27',
        'primary-container': '#00d4ff',
        'tertiary-fixed': '#ffdeae',
        'secondary-fixed-dim': '#b8c8de',
        'on-secondary-fixed-variant': '#39485a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '64px',
        'gutter': '24px',
        'unit': '4px',
        'margin-mobile': '16px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      boxShadow: {
        'neon-glow': '0 0 15px rgba(0, 212, 255, 0.4)',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'headline-xl': ['Montserrat', 'sans-serif'],
        'technical-mono': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
        'headline-xl': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'technical-mono': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
